apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base
patchesStrategicMerge:
  - variables.yaml
  - kubernetes-version.yaml
  - master-replicas.yaml
