---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cc-lab-cluster
spec:
  topology:
    variables:
    - name: cluster
      value:
        bastionEnabled: false
        bastionFlavor: d2-8
        bastionImage: centos_8
        cloud: openstack
        externalNetworkId: b2c02fdc-ffdf-40f6-9722-533bd7058c06
        sshKeyName: arutest
    - name: controlPlane
      value:
        flavorName: d2-8
        volumeSize: 0
        volumeType: classic
    - name: alphaNodePool
      value:
        spec:
          flavorName: d2-8
    workers:
      machineDeployments:
        #      - class: boot-from-volume
        #        failureDomain: nova
        #        name: md-0
        #        replicas: 1
      - class: boot-from-image
        failureDomain: nova
        name: md-1
        replicas: 1
