---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cc-lab-cluster
  labels:
    cloud-provider: openstack
spec:
  topology:
    class: cc-lab
    version: v1.26.4
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: alpha-node-pool
          name: md-0
          replicas: 1
          failureDomain: nova
        - class: beta-node-pool
          name: md-1
          replicas: 1
          failureDomain: nova
    variables:
      - name: cluster
        value:
          externalNetworkId: <external-network-id>
          sshKeyName: <ssh-key>
          cloud: openstack
          bastionEnabled: false
          bastionFlavor: <flavor>
          bastionImage: centos_8
      - name: controlPlane
        value:
          flavorName: <flavor>
          volumeType: __DEFAULT__
          volumeSize: 50
      - name: betaNodePool
        value:
          spec:
            flavorName: <flavor>
            volumeType: __DEFAULT__
            volumeSize: 50
      - name: alphaNodePool
        value:
          spec:
            flavorName: <flavor>
